# Copyright zeroRISC Inc.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

exports_files(["acc_pqc_env_pkg.core"])

filegroup(
    name = "cores",
    srcs = [
        "acc_pqc_env_pkg.core",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "rtl_files",
    srcs = ["acc_pqc_env_pkg.sv"],
    visibility = ["//visibility:public"],
)
