# Copyright zeroRISC Inc.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

filegroup(
    name = "cores",
    srcs = [
        "acc_memutil.core",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "cc_files",
    srcs = [
        "acc_memutil.cc",
        "acc_memutil.h",
        "sv_utils.h",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "doc_files",
    srcs = [
        "README.md",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "rtl_files",
    srcs = ["acc_memutil_pkg.sv"],
    visibility = ["//visibility:public"],
)
