# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

sh_binary(
    name = "run_test",
    srcs = ["run_test.sh"],
)
