# Copyright zeroRISC Inc.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "cores",
    srcs = [
        "acc_top_sim.core",
    ],
)

filegroup(
    name = "cc_files",
    srcs = [
        "acc_top_sim.cc",
    ],
)

filegroup(
    name = "lint_files",
    srcs = [
        "acc_top_sim_waivers.vlt",
    ],
)

filegroup(
    name = "rtl_files",
    srcs = [
        "acc_mock_edn.sv",
        "acc_top_sim.sv",
    ],
)
