// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

`include "dma_base_vseq.sv"
`include "dma_common_vseq.sv"
`include "dma_generic_vseq.sv"
`include "dma_generic_smoke_vseq.sv"
`include "dma_memory_vseq.sv"
`include "dma_memory_smoke_vseq.sv"
`include "dma_handshake_vseq.sv"
`include "dma_handshake_smoke_vseq.sv"
`include "dma_memory_region_lock_vseq.sv"
`include "dma_abort_vseq.sv"
`include "dma_generic_stress_vseq.sv"
`include "dma_memory_stress_vseq.sv"
`include "dma_handshake_stress_vseq.sv"
`include "dma_stress_all_vseq.sv"
`include "dma_short_transfer_vseq.sv"
`include "dma_longer_transfer_vseq.sv"
`include "dma_config_lock_vseq.sv"
`include "dma_mem_enabled_vseq.sv"
`include "dma_hashing_partial_vseq.sv"
`include "dma_overlap_vseq.sv"
`include "dma_memset_vseq.sv"
`include "dma_partial_size_vseq.sv"
`include "dma_range_partial_vseq.sv"
`include "dma_aes_smoke_vseq.sv"
`include "dma_aes_fifo_vseq.sv"
`include "dma_aes_vseq.sv"
`include "dma_aes_error_vseq.sv"
`include "dma_aes_abort_vseq.sv"
`include "dma_aes_clear_mid_commit_vseq.sv"
`include "dma_abort_drain_vseq.sv"
`include "dma_aes_bus_err_vseq.sv"
`include "dma_verify_vseq.sv"
