// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// SECDED encoder generated by util/design/secded_gen.py

module prim_secded_inv_88_80_enc (
  input        [79:0] data_i,
  output logic [87:0] data_o
);

  always_comb begin : p_encode
    data_o = 88'(data_i);
    data_o[80] = ^(data_o & 88'h005F5D72000000001FFFFF);
    data_o[81] = ^(data_o & 88'h00E8F91F00000FFFE0003F);
    data_o[82] = ^(data_o & 88'h00BB07EB003FF003E007C1);
    data_o[83] = ^(data_o & 88'h00FEBAA40FC0F03C207842);
    data_o[84] = ^(data_o & 88'h00B58B5F71C711C4438884);
    data_o[85] = ^(data_o & 88'h00D7E4B9B65926488C9108);
    data_o[86] = ^(data_o & 88'h006377DCDAAA4A91152210);
    data_o[87] = ^(data_o & 88'h000CFEE7ED348D221A4420);
    data_o ^= 88'hAA00000000000000000000;
  end

endmodule : prim_secded_inv_88_80_enc
