# Copyright zeroRISC Inc.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

name: Upload Documentation
on:
  merge_group:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  # Needed for workload identity federation
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  upload_docs:
    name: Upload documentation
    if: ${{ github.event_name != 'pull_request' && github.ref_name == 'master' }}
    needs: build_docs
    runs-on:
      # Requires access to license-server.
      group: pavona-vivado
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v7
        with:
          name: docs
          path: build-site/
      - name: Upload documentation to web server
        run: |
          HOST="$(cat /home/ci/license-server/hostname)"
          KEY_FILE=/tmp/key.pem
          echo ${{ secrets.HTML_UPLOAD_KEY }} > ${KEY_FILE}
          scp -r -i ${KEY_FILE} build-site/book/* "www@${HOST}:public_html/"
